name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-multimc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p config
          mkdir -p defaultconfigs
          mkdir -p mods
          mkdir -p multimc/.minecraft
          cp -r instance.cfg multimc
          cp -r mmc-pack.json multimc
          cp -r mods multimc/.minecraft
          cp -r defaultconfigs multimc/.minecraft
          cp -r config multimc/.minecraft
      - run: zip -r multimc.zip multimc
      - uses: actions/upload-artifact@v3
        with:
          name: multimc
          path: multimc.zip
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install Forge Server
        run: |
          java -jar installer.jar --installServer server
      - name: Copy Mods
        run: |
          mkdir -p config
          mkdir -p defaultconfigs
          mkdir -p mods
          cp -r defaultconfigs ./server/defaultconfigs
          cp -r config ./server/config
          cp -r mods ./server/mods
      - name: Rename server executable to a standard format
        run: |
          mv ./server/libraries/net/minecraftforge/forge/*/forge*server.jar ./server/server.jar

      - run: zip -r server.zip .
        working-directory: server

      - uses: actions/upload-artifact@v3
        with:
          name: server
          path: server/server.zip
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build-multimc
      - build-server
    steps:
      - uses: actions/download-artifact@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: multimc/multimc.zip, server/server.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
